#!/bin/bash
sudo apt-get update -y && sudo apt-get -y install curl tar ca-certificates
curl -o apphub-linux-386.tar.gz https://assets.coreservice.io/public/package/70/app-market-gaga-pro/1.0.4/app-market-gaga-pro-1_0_4.tar.gz && tar -zxf apphub-linux-386.tar.gz && rm -f apphub-linux-386.tar.gz && cd ./apphub-linux-386
sudo ./apphub service remove && sudo ./apphub service install
./apphub status
sleep 2
./apphub status
sleep 2
sudo ./apps/gaganode/gaganode config set --token=eeovnkyizrwinjgi78a43d1fb206d818
./apphub restart
